train_path: "/work/c-2iia/sp165339/Liver_Segmentation_3D/3D_Data_128/train"
val_path: "/work/c-2iia/sp165339/Liver_Segmentation_3D/3D_Data_128/val"

# train_path: "C:/Users/penda/Documents/Study Materials/Machine and Deep Learning/Project/3D_Data_128/train"
# val_path: "C:/Users/penda/Documents/Study Materials/Machine and Deep Learning/Project/3D_Data_128/val"

n_classes: 3
img_channels: 1
